name: Build APK
on:
  workflow_dispatch:
    inputs:
      file_id:
        description: 'Enter your Google Drive File ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gdown
      run: pip install gdown

    - name: Try gdown with full URL
      run: |
        gdown "https://drive.google.com/file/d/${{ github.event.inputs.file_id }}/view?usp=sharing" -O project.zip || \
        wget --no-check-certificate "https://drive.google.com/uc?export=download&id=${{ github.event.inputs.file_id }}&confirm=t" -O project.zip

    - name: Unzip project
      run: unzip project.zip -d project

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Build APK
      run: |
        cd project/project
        gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: My-App
        path: project/project/app/build/outputs/apk/debug/*.apk
